// <auto-generated />
using Lms.CourseService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lms.CourseService.Infrastructure.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20260526130414_SeedCourses")]
    partial class SeedCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lms.CourseService.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn digital marketing fundamentals",
                            Duration = "1 hr 16 min",
                            ImageUrl = "https://example.com/image1.jpg",
                            Instructor = "John Doe",
                            LessonsCount = 5,
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Introduction to UI/UX design",
                            Duration = "2 hr 30 min",
                            ImageUrl = "https://example.com/image2.jpg",
                            Instructor = "Jane Smith",
                            LessonsCount = 8,
                            Title = "UI/UX Design"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
