// <auto-generated />
using System;
using Lms.CourseService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lms.CourseService.Infrastructure.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20260601140832_AddPopularCourses")]
    partial class AddPopularCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lms.CourseService.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Artificial Intelligence course",
                            Duration = "3 hr 45 min",
                            ImageUrl = "/ai-small.svg",
                            Instructor = "Alice Johnson",
                            LessonsCount = 10,
                            Title = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Data Science & Analytics course",
                            Duration = "1 hr 50 min",
                            ImageUrl = "/data-science-small.svg",
                            Instructor = "Bob Brown",
                            LessonsCount = 6,
                            Title = "Data Science & Analytics"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Learn digital marketing fundamentals",
                            Duration = "1 hr 16 min",
                            ImageUrl = "/digital-marketing-small.svg",
                            Instructor = "John Doe",
                            LessonsCount = 5,
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Introduction to UI/UX design",
                            Duration = "2 hr 30 min",
                            ImageUrl = "/ui-ux-small.svg",
                            Instructor = "Jane Smith",
                            LessonsCount = 8,
                            Title = "UI/UX Design"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Learn full stack development",
                            Duration = "2 hr 20 min",
                            ImageUrl = "/full-stack-small.svg",
                            Instructor = "Charlie Davis",
                            LessonsCount = 7,
                            Title = "Full stack Developer "
                        },
                        new
                        {
                            Id = 6,
                            Description = "Introduction to sketching for designers",
                            Duration = "3 hr 10 min",
                            ImageUrl = "/sketch-small.svg",
                            Instructor = "Diana Evans",
                            LessonsCount = 9,
                            Title = "Sketch for Designer"
                        });
                });

            modelBuilder.Entity("Lms.CourseService.Domain.Entities.PopularCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PopularCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconUrl = "/courseImages/graphic-d-icon.svg",
                            Subtitle = "Creating Visual Content",
                            Title = "Graphic Design"
                        },
                        new
                        {
                            Id = 2,
                            IconUrl = "/courseImages/uiux-d-icon.svg",
                            Subtitle = "Combines User Interface (UI)",
                            Title = "UI/UX Design"
                        },
                        new
                        {
                            Id = 3,
                            IconUrl = "/courseImages/brand-i-icon.svg",
                            Subtitle = "The Collection of Visual",
                            Title = "Brand Identity"
                        },
                        new
                        {
                            Id = 4,
                            IconUrl = "/courseImages/web-d-icon.svg",
                            Subtitle = "Process of Creating Websites",
                            Title = "Web Design"
                        });
                });

            modelBuilder.Entity("Lms.CourseService.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
